name: Scrape CSFloat Prices

on:
  workflow_dispatch: # Allows you to run it manually from the Actions tab
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: python -m playwright install --with-deps

      - name: Run scraper
        run: python scrape_prices.py

      - name: Commit and push if changed
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add item_overrides.json
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated price update"
            git push
          fi
